### ISSUE TITLE
Active Directory windows, can't authenticate.  

### ISSUE THREAD

**Issue by jeremiahsherrill** [jotaelesalinas/laravel-simple-ldap-auth#28]
Laravel Version: 5.7
Adldap2-Laravel Version: 5.0.2
PHP Version: 7.2
LDAP Type: ActiveDirectory

I have a rails app working fine with it and here are the rails app settings 

```
authorizations: &AUTHORIZATIONS
  allow_unauthenticated_bind: false
  group_base: ou=groups,dc=mydc1,dc=mydc2
  required_groups: "All Adams"
name
  require_attribute:
    objectClass: inetOrgPerson
    authorizationRole: postsAdmin
development:
  host: myhost
  port: 389
  attribute: samaccountname
  base: dc=mydc1,dc=mydc2
  ssl: false
  <<: *AUTHORIZATIONS
```

these are my env settings for ldap for laravel
```
LDAP_SCHEMA=default
LDAP_HOSTS=myhost
LDAP_BASE_DN=ou=Users,ou=Accounts,dc=mydc1,dc=mydc2
LDAP_USER_ATTRIBUTE=uid
LDAP_USER_FORMAT=uid=%s,dc=mydc1,dc=mydc2
LDAP_CONNECTION=default
```

I got your demo to work just fine and it authenticates.   All I get back when I attempt to connect is "These credentials do not match our records."

I am really at a loss, I am sure it's probably something pretty simple that I am missing, but any help would be appreciated.
